description: This is a StackSpot Stack with plugins of research tools that aim to ease software development.
name: stk-research
display-name: stk-research
picture: stack.png
category: Analytics # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - Java
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies 
  - Java 
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml
